# Generated by Django 4.2 on 2025-04-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
